### ISSUE TITLE
ARM架构支持请求

### ISSUE THREAD

**Issue by WorldlineChanger** [DDSRem/easyimage#2]
能否增加arm64系统的Docker镜像支持？非常感谢

**Comment by DDSRem** [comment]
准备添加，这周末出arm镜像

**Comment by leealu** [comment]
我是甲骨文的arm,装了以后ddsderek/easyimage                "/start.sh"              2 minutes ago   Restarting (1) 26 seconds ago ,是不是目前还不支持?
